#!/bin/bash
# chkconfig: 2345 55 25
# description: Nginx Service

### BEGIN INIT INFO
# Provides:          nginx
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts nginx
# Description:       starts the nginx web server
### END INIT INFO

nginx_path=/www/server/nginx
nginx_bin=$nginx_path/sbin/nginx
nginx_conf=$nginx_path/conf/nginx.conf
nginx_pid=$nginx_path/logs/nginx.pid

case "$1" in
    start)
        if [ -f $nginx_pid ]; then
            echo "Nginx is already running"
            exit 0
        fi
        echo "Starting Nginx..."
        $nginx_bin -c $nginx_conf
        ;;
    stop)
        if [ ! -f $nginx_pid ]; then
            echo "Nginx is not running"
            exit 0
        fi
        echo "Stopping Nginx..."
        kill -QUIT $(cat $nginx_pid)
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    reload)
        if [ ! -f $nginx_pid ]; then
            echo "Nginx is not running"
            exit 1
        fi
        echo "Reloading Nginx..."
        kill -HUP $(cat $nginx_pid)
        ;;
    status)
        if [ -f $nginx_pid ]; then
            echo "Nginx is running (pid: $(cat $nginx_pid))"
        else
            echo "Nginx is not running"
        fi
        ;;
    test)
        $nginx_bin -t -c $nginx_conf
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload|status|test}"
        exit 1
        ;;
esac
